import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F9F8FD',
  },
  container: {
    flex: 1,
    backgroundColor: '#F9F8FD',
  },
  scrollView: {
    flex: 1,
  },
  hudBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderBottomWidth: 1.5,
    borderBottomColor: '#E2DFF0',
    backgroundColor: '#FFFFFF',
  },
  hudTitleContainer: {
    flexDirection: 'column',
    flexShrink: 1,
    marginRight: 8,
  },
  hudTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#2A2738',
    letterSpacing: 0.5,
  },
  hudSubTitle: {
    fontSize: 13,
    color: '#5E43F3',
    fontWeight: '600',
    marginTop: 4,
    letterSpacing: 0.5,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 24,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderWidth: 1.5,
    flexShrink: 0,
  },
  statusBadgeConnected: {
    backgroundColor: '#E3FAF0',
    borderColor: '#A3EAD0',
  },
  statusBadgeConnecting: {
    backgroundColor: '#FFF1E6',
    borderColor: '#FFD8B3',
  },
  statusBadgeDisconnected: {
    backgroundColor: '#FFEBEF',
    borderColor: '#FFCCD6',
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  statusDotConnected: {
    backgroundColor: '#00875A',
  },
  statusDotConnecting: {
    backgroundColor: '#D97706',
  },
  statusDotDisconnected: {
    backgroundColor: '#DE350B',
  },
  statusLabel: {
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  statusLabelConnected: {
    color: '#00875A',
  },
  statusLabelConnecting: {
    color: '#D97706',
  },
  statusLabelDisconnected: {
    color: '#DE350B',
  },
  statusBadgeCalibrated: {
    backgroundColor: '#E3FAF0',
    borderColor: '#A3EAD0',
  },
  statusBadgeUncalibrated: {
    backgroundColor: '#FFF4E5',
    borderColor: '#FFD8B3',
  },
  statusLabelCalibrated: {
    color: '#00875A',
  },
  statusLabelUncalibrated: {
    color: '#D97706',
  },
  calibrationCardWarning: {
    backgroundColor: '#FFF4E5',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#FFD8B3',
    marginVertical: 12,
  },
  calibrationCardSuccess: {
    backgroundColor: '#E3FAF0',
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
    borderColor: '#A3EAD0',
    marginVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  calibrationWarningHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  calibrationWarningTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#D97706',
  },
  calibrationWarningText: {
    fontSize: 13,
    color: '#92400E',
    lineHeight: 18,
    marginBottom: 12,
  },
  calibrationCalibrateButton: {
    backgroundColor: '#D97706',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  calibrationCalibrateButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  calibrationSuccessTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#00875A',
  },
  calibrationSuccessSubText: {
    fontSize: 12,
    color: '#065F46',
    marginTop: 2,
  },
  recalibrateButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#A3EAD0',
  },
  recalibrateButtonText: {
    color: '#00875A',
    fontSize: 12,
    fontWeight: '700',
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 50,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 22,
    marginBottom: 18,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
    overflow: 'hidden',
    position: 'relative',
  },
  cardHeaderAccent: {
    position: 'absolute',
    top: 0,
    left: 20,
    right: 20,
    height: 4,
    borderBottomLeftRadius: 4,
    borderBottomRightRadius: 4,
  },
  cardSectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#2A2738',
    letterSpacing: 0.5,
    marginBottom: 16,
    marginTop: 2,
  },
  segmentedContainer: {
    flexDirection: 'row',
    backgroundColor: '#F4F3F8',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 10,
  },
  segmentButtonActive: {
    backgroundColor: '#5E43F3',
  },
  segmentText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#5E43F3',
    letterSpacing: 0.5,
  },
  segmentTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  inputsRow: {
    flexDirection: 'row',
    marginBottom: 16,
  },
  inputLabel: {
    color: '#4E4B66',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  input: {
    backgroundColor: '#F4F3F8',
    borderRadius: 12,
    color: '#2A2738',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1.5,
    borderColor: '#D1CCE6',
    fontSize: 16,
    letterSpacing: 0.5,
  },
  bluetoothGroup: {
    marginBottom: 16,
  },
  scanButtonFull: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#5E43F3',
    backgroundColor: '#F3F0FC',
    alignItems: 'center',
  },
  scanButtonDisabled: {
    borderColor: '#B6AEE6',
    backgroundColor: '#F4F3F8',
    opacity: 0.6,
  },
  scanningLoaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  scanButtonText: {
    color: '#5E43F3',
    fontSize: 16,
    fontWeight: '700',
  },
  deviceList: {
    marginTop: 12,
    backgroundColor: '#F4F3F8',
    borderRadius: 14,
    padding: 8,
  },
  deviceItem: {
    padding: 14,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    marginBottom: 8,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  deviceItemSelected: {
    borderColor: '#5E43F3',
    backgroundColor: '#F3F0FC',
  },
  deviceRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  deviceIcon: {
    fontSize: 20,
    marginRight: 10,
  },
  deviceInfoContainer: {
    flex: 1,
  },
  deviceName: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2A2738',
  },
  deviceAddress: {
    fontSize: 13,
    color: '#706B8E',
    marginTop: 2,
  },
  emptyContainer: {
    padding: 20,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 15,
    color: '#706B8E',
    textAlign: 'center',
  },
  loadingScriptsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  connectButton: {
    backgroundColor: '#5E43F3',
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  disconnectButton: {
    backgroundColor: '#DE350B',
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  buttonDisabled: {
    backgroundColor: '#D1CCE6',
    opacity: 0.8,
  },
  errorContainer: {
    backgroundColor: '#FFEBEF',
    borderRadius: 12,
    padding: 14,
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: '#FFCCD6',
  },
  errorText: {
    color: '#DE350B',
    fontSize: 14,
    fontWeight: '600',
  },
  divider: {
    height: 1.5,
    backgroundColor: '#E2DFF0',
    marginVertical: 18,
  },
  pingButton: {
    backgroundColor: '#F4F3F8',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#D1CCE6',
  },
  pingButtonText: {
    color: '#5E43F3',
    fontSize: 15,
    fontWeight: '700',
  },
  scriptListContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 10,
  },
  scriptChip: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: '#F4F3F8',
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  scriptChipSelected: {
    backgroundColor: '#5E43F3',
    borderColor: '#5E43F3',
  },
  scriptChipText: {
    color: '#5E43F3',
    fontSize: 14,
    fontWeight: '600',
  },
  scriptChipTextSelected: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  runButton: {
    backgroundColor: '#5E43F3',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  stopButton: {
    backgroundColor: '#DE350B',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  runningBadge: {
    backgroundColor: '#FFEBEF',
    borderRadius: 12,
    padding: 14,
    marginTop: 12,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#FFCCD6',
  },
  runningText: {
    color: '#DE350B',
    fontSize: 14,
    fontWeight: '700',
  },
  categoryTabsContainer: {
    flexDirection: 'row',
    backgroundColor: '#F4F3F8',
    borderRadius: 12,
    padding: 4,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
    marginVertical: 10,
    flexWrap: 'wrap',
    gap: 4,
  },
  categoryTabButton: {
    flex: 1,
    minWidth: 110,
    paddingVertical: 9,
    paddingHorizontal: 8,
    alignItems: 'center',
    borderRadius: 8,
    backgroundColor: 'transparent',
  },
  categoryTabButtonActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#5E43F3',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  categoryTabText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4E4B66',
  },
  categoryTabTextActive: {
    color: '#5E43F3',
  },
  subCategoryContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginVertical: 8,
  },
  subCategoryPill: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 16,
    backgroundColor: '#FAF9FC',
    borderWidth: 1,
    borderColor: '#E2DFF0',
  },
  subCategoryPillActive: {
    backgroundColor: '#EDE9FE',
    borderColor: '#5E43F3',
  },
  subCategoryText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6B7280',
  },
  subCategoryTextActive: {
    color: '#5E43F3',
    fontWeight: '700',
  },
  activityCardsGrid: {
    flexDirection: 'column',
    gap: 8,
    marginTop: 10,
  },
  activityCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  activityCardSelected: {
    borderColor: '#5E43F3',
    backgroundColor: '#F7F5FE',
  },
  activityCardIcon: {
    fontSize: 24,
    width: 36,
    textAlign: 'center',
  },
  activityCardContent: {
    flex: 1,
  },
  activityCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginBottom: 2,
  },
  activityCardTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E1B4B',
    flexShrink: 1,
  },
  activityCardTitleSelected: {
    color: '#5E43F3',
  },
  activityCardBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    backgroundColor: '#EDE9FE',
  },
  activityCardBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#5E43F3',
    textTransform: 'uppercase',
  },
  activityCardDesc: {
    fontSize: 11,
    color: '#6B7280',
    lineHeight: 15,
  },
  activityDetailCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginTop: 14,
  },
  activityDetailHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  activityDetailTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
  },
  activityDetailTarget: {
    fontSize: 11,
    color: '#9CA3AF',
    fontFamily: 'monospace',
    marginTop: 4,
  },
  consoleToolbar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  filterContainer: {
    flexDirection: 'row',
    gap: 6,
  },
  filterChip: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: '#F4F3F8',
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  filterChipActive: {
    backgroundColor: '#5E43F3',
    borderColor: '#5E43F3',
  },
  filterChipText: {
    fontSize: 12,
    color: '#5E43F3',
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  flushButton: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: '#FFEBEF',
    borderWidth: 1.5,
    borderColor: '#FFCCD6',
  },
  clearText: {
    fontSize: 12,
    color: '#DE350B',
    fontWeight: '700',
  },
  consoleContainer: {
    backgroundColor: '#F4F3F8',
    borderRadius: 16,
    padding: 14,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
    minHeight: 250,
  },
  consoleScrollView: {
    flex: 1,
  },
  consoleEmptyContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 50,
  },
  consolePlaceholder: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4E4B66',
    marginBottom: 6,
  },
  consoleSubPlaceholder: {
    fontSize: 13,
    color: '#706B8E',
  },
  logText: {
    fontFamily: 'monospace',
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 6,
  },
  logInfo: {
    color: '#0052CC',
  },
  logSuccess: {
    color: '#00875A',
  },
  logError: {
    color: '#DE350B',
  },
  logRaw: {
    color: '#4E4B66',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1.5,
    borderBottomColor: '#E2DFF0',
  },
  tabButton: {
    flex: 1,
    paddingVertical: 16,
    alignItems: 'center',
    borderBottomWidth: 3,
    borderBottomColor: 'transparent',
  },
  tabButtonActive: {
    borderBottomColor: '#5E43F3',
  },
  tabButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4E4B66',
  },
  tabButtonTextActive: {
    color: '#5E43F3',
  },
  multilineInput: {
    minHeight: 80,
    textAlignVertical: 'top',
  },
  exampleHeader: {
    fontSize: 15,
    fontWeight: '700',
    color: '#4E4B66',
    marginBottom: 10,
  },
  exampleRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  exampleChip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: '#F3F0FC',
    borderWidth: 1.5,
    borderColor: '#D1CCE6',
  },
  exampleChipText: {
    fontSize: 14,
    color: '#5E43F3',
    fontWeight: '600',
  },
  metaRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  metaCol: {
    flex: 1,
  },
  emptySubText: {
    fontSize: 13,
    color: '#706B8E',
    marginTop: 6,
  },
  stepItemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  stepItemCanned: {
    borderLeftWidth: 6,
    borderLeftColor: '#5E43F3',
  },
  stepItemOpen: {
    borderLeftWidth: 6,
    borderLeftColor: '#00875A',
  },
  stepItemHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
    flexWrap: 'wrap',
    gap: 8,
  },
  stepBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  stepIndexText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#2A2738',
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeCanned: {
    backgroundColor: '#F3F0FC',
  },
  badgeOpen: {
    backgroundColor: '#E3FAF0',
  },
  badgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  stepTypeToggleRow: {
    flexDirection: 'row',
    backgroundColor: '#F4F3F8',
    borderRadius: 10,
    padding: 3,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  stepTypeToggleBtn: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  stepTypeToggleBtnActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  stepTypeToggleBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#2A2738',
  },
  stepItemBody: {
    marginTop: 8,
  },
  stepInputLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: '#4E4B66',
    marginTop: 10,
    marginBottom: 6,
  },
  removeStepBtn: {
    alignSelf: 'flex-end',
    marginTop: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#FFEBEF',
  },
  removeStepBtnText: {
    color: '#DE350B',
    fontSize: 13,
    fontWeight: '700',
  },
  addStepButton: {
    width: '100%',
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#5E43F3',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginBottom: 20,
  },
  addStepButtonText: {
    color: '#5E43F3',
    fontSize: 15,
    fontWeight: '700',
  },
  syncButton: {
    backgroundColor: '#00875A',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  runPlanButton: {
    backgroundColor: '#5E43F3',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  planSyncHint: {
    fontSize: 13,
    color: '#706B8E',
    textAlign: 'center',
    marginTop: 8,
    lineHeight: 18,
  },
  subStepCard: {
    backgroundColor: '#F4F3F8',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  subStepHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  subStepIndexText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#2A2738',
  },
  removeSubStepText: {
    color: '#DE350B',
    fontSize: 13,
    fontWeight: '700',
  },
  subStepInputLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#4E4B66',
    marginTop: 8,
    marginBottom: 4,
  },
  subStepTextInput: {
    fontSize: 15,
    paddingVertical: 8,
  },
  subStepRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  subStepCol: {
    flex: 1,
  },
  subStepImageContainer: {
    marginTop: 10,
    padding: 10,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  urlLoadedText: {
    color: '#00875A',
    fontSize: 13,
    fontWeight: '600',
  },
  urlPendingText: {
    color: '#706B8E',
    fontSize: 13,
    marginTop: 8,
  },
  subStepAddImageBtn: {
    marginTop: 8,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#5E43F3',
    backgroundColor: '#F3F0FC',
    alignItems: 'center',
  },
  subStepAddImageBtnText: {
    color: '#5E43F3',
    fontSize: 13,
    fontWeight: '700',
  },
  addSubStepBtn: {
    width: '100%',
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#5E43F3',
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    marginTop: 8,
    marginBottom: 8,
  },
  addSubStepBtnText: {
    color: '#5E43F3',
    fontSize: 14,
    fontWeight: '700',
  },
  imageAssetRow: {
    flexDirection: 'row',
    padding: 14,
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
    alignItems: 'center',
    gap: 12,
  },
  imageAssetInfo: {
    flex: 1,
  },
  imageAssetFilename: {
    fontSize: 15,
    fontWeight: '700',
    color: '#2A2738',
  },
  imageAssetStep: {
    fontSize: 13,
    color: '#706B8E',
    marginTop: 2,
  },
  imageAssetPromptInput: {
    fontSize: 14,
    marginTop: 8,
    minHeight: 50,
  },
  imageAssetUrl: {
    fontSize: 12,
    color: '#00875A',
    marginTop: 4,
  },
  imageAssetStatusPending: {
    fontSize: 13,
    color: '#706B8E',
    marginTop: 4,
  },
  imageAssetActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  imageAssetBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#5E43F3',
  },
  imageAssetBtnRegen: {
    backgroundColor: '#F3F0FC',
    borderWidth: 1.5,
    borderColor: '#5E43F3',
  },
  imageAssetBtnText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '700',
  },
  imageAssetBtnDisabled: {
    backgroundColor: '#D1CCE6',
  },
  imageSizeSelectorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  segmentedContainerSize: {
    flexDirection: 'row',
    backgroundColor: '#F4F3F8',
    borderRadius: 8,
    padding: 2,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
  },
  segmentButtonSize: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  segmentButtonActiveSize: {
    backgroundColor: '#5E43F3',
  },
  segmentTextSize: {
    fontSize: 12,
    color: '#5E43F3',
    fontWeight: '600',
  },
  segmentTextActiveSize: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  authContainer: {
    flex: 1,
    backgroundColor: '#F9F8FD',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  authCard: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    borderWidth: 1.5,
    borderColor: '#E2DFF0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 4,
    alignItems: 'center',
  },
  authEmoji: {
    fontSize: 48,
    marginBottom: 14,
  },
  authTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#2A2738',
    marginBottom: 6,
  },
  authSubtitle: {
    fontSize: 14,
    color: '#706B8E',
    textAlign: 'center',
    marginBottom: 20,
  },
  authInput: {
    width: '100%',
    backgroundColor: '#F4F3F8',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#D1CCE6',
    padding: 12,
    fontSize: 18,
    textAlign: 'center',
    color: '#2A2738',
    marginBottom: 12,
  },
  authErrorText: {
    color: '#DE350B',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 12,
  },
  authBtn: {
    width: '100%',
    backgroundColor: '#5E43F3',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  authBtnText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
});
